# Max Brizzio
# I pledge my honor that I have abided by the Stevens Honor System.

all: 
	gcc -g -Wall -Werror -pedantic-errors $(wildcard *.c) -o $(patsubst %.c,%,$(wildcard *.c))

clean:
	rm -f $(patsubst %.c,%,$(wildcard *.c)) $(patsubst %.c,%,$(wildcard *.c)).exe